### ISSUE TITLE
Default k6 bucket is not created via openKv()

### ISSUE THREAD

**Issue by deejiw** [oleiade/xk6-kv#1]
By default, `k6` bucket is not being created and therefore `db` failed to operate.

I did add the following code snippet as per [forked branch](https://github.com/deejiw/xk6-kv/tree/v0.0.1).

Since this repository does not allow public to open a new branch for pull request, I am opening this issue to address changes instead.

Thank you.

**Comment by oleiade** [comment]
I believe this issue should be addressed in the latest state of the `main` branch. Would you be so kind to take it for a spin and let me know if that works for you? 🙇🏻

**Comment by deejiw** [comment]
Yep it is working. Closing this issue.
