### ISSUE TITLE
xk6 build fails for v0.53.0

### ISSUE THREAD

**Issue by kevin-prohn** [oleiade/xk6-kv#3]
Running the xk6 build against k6 v0.53.0 will fail, because this version includes the switch from goja to sobek. 

`xk6 build --with github.com/oleiade/xk6-kv@main` works correctly as https://github.com/oleiade/xk6-kv/pull/2 already fixed the issue.

Can you create a new tag / release including that change?

**Comment by oleiade** [comment]
Hey @kevin-prohn 👋🏻 Sure thing!

**Comment by kevin-prohn** [comment]
Thanks, it's working now.
